# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: main

on: [push, workflow_dispatch]

defaults:
    run:
        shell: cmd

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run test.cmd
                run: test.cmd
